input_root: /dataMeR2/phil/data/midterm/parquet
output_root: /dataMeR2/phil/data/midterm/bio_embeddings/gte-multilingual-base/version=v001

gpus: "0,1,2,3"
num_workers: 4
batch_size: 2048

duckdb_memory_limit: 200GB
duckdb_threads: 32
