input_root: /dataMeR1/phil/data/twibot20/parquet
output_root: /dataMeR1/phil/data/twibot20/bio_embeddings/gte-multilingual-base/version=v001

gpus: "0"
num_workers: 1
batch_size: 512

duckdb_memory_limit: 200GB
duckdb_threads: 32
